// ============================================================
// PUSATPERIZINAN.COM — DIREKTORI INSTANSI / KANAL RESMI
// 20 kementerian, lembaga & otoritas yang kami urus setiap hari
// Dipakai di: section homepage (marquee), /kanal-resmi, JSON-LD
// ============================================================

export interface Institution {
  id: string;
  initials: string; // monogram dalam seal
  name: string; // nama pendek (badge)
  fullName: string; // nama resmi lengkap
  role: string; // wewenang utama dalam 1 baris
  desc: string; // 2-3 kalimat: apa yang kami urus di instansi ini
  color: string; // warna brand (hex) untuk seal
  website: string; // situs resmi
  websiteLabel: string;
  services: string[]; // slug layanan internal terkait
  serviceLabels: string[]; // label chip (urut sesuai services)
}

export const INSTITUTIONS: Institution[] = [
  {
    id: "kemenkumham",
    initials: "K&HAM",
    name: "Kemenkumham",
    fullName: "Kementerian Hukum dan HAM Republik Indonesia",
    role: "Pencatatan badan hukum & SK pendirian",
    desc: "Semi hari kami memproses pengesahan akta pendirian, perubahan susunan pengurus, sampai persetujuan Menkumham untuk PT, CV, yayasan, dan koperasi. Sistem AHU Online yang kami kuasai menentukan kecepatan legalitas badan usaha Anda.",
    color: "#1E3A5F",
    website: "https://ahu.kemenkumham.go.id",
    websiteLabel: "ahu.kemenkumham.go.id",
    services: ["pt", "cv", "koperasi-yayasan", "pt-perorangan"],
    serviceLabels: ["Pendirian PT & PMA", "Pendirian CV", "Yayasan & Koperasi", "PT Perorangan"],
  },
  {
    id: "djp",
    initials: "DJP",
    name: "DJP Kemenkeu",
    fullName: "Direktorat Jenderal Pajak — Kementerian Keuangan RI",
    role: "NPWP, SPT, PKP, Coretax DJP",
    desc: "Dari pendaftaran NPWP elektronik, pengukuhan PKP, lapor SPT Masa & Tahunan, sampai seluruh fitur Coretax DJP — tim pajak kami mengoperasikan semua kanal resmi DJP setiap hari untuk klien pribadi, UMKM, dan korporat.",
    color: "#F26522",
    website: "https://www.pajak.go.id",
    websiteLabel: "pajak.go.id",
    services: ["tax-npwp-op", "tax-spt-op", "tax-pkp-badan", "tax-umkm"],
    serviceLabels: ["NPWP Pribadi", "SPT Tahunan OP", "PKP Badan", "Pajak UMKM 0,5%"],
  },
  {
    id: "oss-rba",
    initials: "OSS",
    name: "OSS-RBA",
    fullName: "Online Single Submission — Risk Based Approach",
    role: "NIB & seluruh perizinan berusaha",
    desc: "OSS-RBA adalah gerbang utama perizinan berusaha Indonesia: NIB, sertifikat standar, sampai izin berusaha berbasis risiko. Kami menangani pembuatan akun, penyesuaian KBLI & risiko usaha, penyelarasan simpul izin, sampai LKPM rutin.",
    color: "#0F8B8D",
    website: "https://oss.go.id",
    websiteLabel: "oss.go.id",
    services: ["nib", "lkpm", "b3-proper"],
    serviceLabels: ["NIB & OSS-RBA", "Laporan LKPM", "B3 & PROPER"],
  },
  {
    id: "bkpm",
    initials: "BKPM",
    name: "Kementerian Investasi",
    fullName: "Kementerian Investasi / Badan Koordinasi Penanaman Modal (BKPM)",
    role: "Investasi asing (PMA) & fasilitasi iklim usaha",
    desc: "Penanaman modal asing berpindah ke runtutan OSS-RBA di bawah kementerian investasi. Kami membantu struktur PMA, permodalan disetor, pelaporan kegiatan penanaman modal, sampai fasilitas penyederhanaan perizinan untuk proyek prioritas.",
    color: "#003D79",
    website: "https://www.bkpm.go.id",
    websiteLabel: "bkpm.go.id",
    services: ["pt", "ekspansi-asing"],
    serviceLabels: ["PT PMA", "Ekspansi Modal Asing"],
  },
  {
    id: "bpjph",
    initials: "BPJPH",
    name: "BPJPH",
    fullName: "Badan Penyelenggara Jaminan Produk Halal — Kemenag RI",
    role: "Sertifikasi halal produk (SIHALAL & SEHATI)",
    desc: "Semua sertifikasi halal klien kami diproses lewat sistem SIHALAL milik BPJPH: self-declare untuk UMKM (gratis) dan jalur reguler. Kami mendampingi input daftar bahan, koordinasi audit LPH, sampai kewajiban memelihara kehalalan pasca-terbit.",
    color: "#1B7A43",
    website: "https://bpjph.halal.go.id",
    websiteLabel: "halal.go.id",
    services: ["halal"],
    serviceLabels: ["Sertifikasi Halal"],
  },
  {
    id: "kemenag",
    initials: "KAG",
    name: "Kemenag",
    fullName: "Kementerian Agama Republik Indonesia",
    role: "Izin perjalanan ibadah (PPIU & PPIH)",
    desc: "Travel umroh dan penyelenggara haji khusus diawasi Kemenag lewat sistem Romantis: izin PPIU/PPIH, SKAI amplop, laporan keberangkatan jemaah, dan penilaian layanan. Kami mengurus semuanya sampai travel Anda legal penuh.",
    color: "#005B41",
    website: "https://kemenag.go.id",
    websiteLabel: "kemenag.go.id",
    services: ["ppi-umroh", "ppi-haji"],
    serviceLabels: ["Izin Umroh PPIU", "Izin Haji PPIH"],
  },
  {
    id: "bpom",
    initials: "BPOM",
    name: "BPOM",
    fullName: "Badan Pengawas Obat dan Makanan RI",
    role: "Notifikasi & izin edar MD/BP",
    desc: "Notifikasi kosmetik, obat tradisional, suplemen, dan izin edar pangan diproses di sistem OSS-BPOM. Kami bantu audit label & klaim dulu, siapkan dokumen CPKB/CPOBT, sampai nomor MD/BP terbit — agar produk legal masuk marketplace dan ritel modern.",
    color: "#00695C",
    website: "https://www.pom.go.id",
    websiteLabel: "pom.go.id",
    services: ["bpom", "alkes"],
    serviceLabels: ["Izin BPOM", "Alat Kesehatan"],
  },
  {
    id: "kemenkes",
    initials: "KES",
    name: "Kemenkes",
    fullName: "Kementerian Kesehatan RI",
    role: "Izin usaha kesehatan & standar sarana",
    desc: "Izin usaha klinik, standar sarana fisik, sampai STTK tenaga medis kami kelola lewat kanal Kemenkes/Dinkes. Verifikasi sarana kami bedah sebelum pemeriksa datang — klien kami lolos verifikasi sekali jalan.",
    color: "#00777B",
    website: "https://kemkes.go.id",
    websiteLabel: "kemkes.go.id",
    services: ["kesehatan", "alkes"],
    serviceLabels: ["Izin Klinik & Kesehatan", "Alat Kesehatan"],
  },
  {
    id: "kemnaker",
    initials: "NAK",
    name: "Kemnaker",
    fullName: "Kementerian Ketenagakerjaan RI",
    role: "RPTKA/KITAS asing, LPK & perusahaan penempatan PMI",
    desc: "Izin mempekerjakan tenaga kerja asing (RPTKA & KITAS), izin LPK, sampai izin perusahaan pengiriman PMI (PPTKIS) kami urus di Kemnaker. Regulasi ketenagakerjaan sering berubah — kami yang memantau, Anda yang tenang.",
    color: "#C62828",
    website: "https://kemnaker.go.id",
    websiteLabel: "kemnaker.go.id",
    services: ["rptka-kitas", "lpk-pmi", "pptkis"],
    serviceLabels: ["RPTKA & KITAS", "Izin LPK", "Izin PPTKIS"],
  },
  {
    id: "bnp2mi",
    initials: "B2MI",
    name: "BNP2MI",
    fullName: "Badan Nasional Pelindungan Pekerja Migran Indonesia",
    role: "Pelindungan PMI & SISKOP2MI",
    desc: "Setiap PMI yang kami kirim tercatat di SISKOP2MI dan terlindungi sesuai UU 18/2017. Kami mendampingi penerbitan paspor & dokumen perjalanan, pembekalan pra-keberangkatan, sampai eskalasi pelindungan saat PMI bermasalah di luar negeri.",
    color: "#8E2424",
    website: "https://www.bnp2mi.go.id",
    websiteLabel: "bnp2mi.go.id",
    services: ["dokumen-pmi", "keberangkatan-pmi", "purna-pmi"],
    serviceLabels: ["Dokumen PMI", "Keberangkatan PMI", "Purna PMI"],
  },
  {
    id: "esdm",
    initials: "ESDM",
    name: "Kementerian ESDM",
    fullName: "Kementerian Energi dan Sumber Daya Mineral RI",
    role: "RKAB, WIUP & perizinan minerba",
    desc: "Rencana Kerja dan Anggaran Biaya (RKAB) via Online MUBA, perizinan wilayah izin usaha pertambangan, sampai kepatuhan produksi minerba kami serahkan ke konsultan sektor yang benar-benar paham bahasanya — bukan admin template.",
    color: "#1A5276",
    website: "https://www.esdm.go.id",
    websiteLabel: "esdm.go.id",
    services: ["rkab-tambang", "tambang"],
    serviceLabels: ["RKAB Minerba", "Izin Tambang"],
  },
  {
    id: "lpjk",
    initials: "LPJK",
    name: "LPJK",
    fullName: "Lembaga Pengembangan Jasa Konstruksi",
    role: "Sertifikat Badan Usaha (SBU) jasa konstruksi",
    desc: "SBU menentukan paket tender mana yang boleh Anda ikuti. Kami audit portofolio & tenaga teknik Anda dulu, pilih sub-bidang dan kualifikasi yang tepat, lalu proses sertifikatnya — kontraktor kami menang tender karena SBU yang benar sejak awal.",
    color: "#2E7D32",
    website: "https://lpjk.or.id",
    websiteLabel: "lpjk.or.id",
    services: ["smk3", "pbg"],
    serviceLabels: ["SMK3 Konstruksi", "PBG untuk Kontraktor"],
  },
  {
    id: "kemenpu",
    initials: "PU",
    name: "Kementerian PU",
    fullName: "Kementerian Pekerjaan Umum RI",
    role: "PBG & SLF bangunan gedung (SimBG)",
    desc: "Persetujuan Bangunan Gedung dan Sertifikat Laik Fungsi kami proses lewat SimBG: gambar teknik standar, perhitungan struktur, sampai koordinasi verifikasi. Gedung Anda layak fungsi — bank, asuransi, dan tender terbuka.",
    color: "#E8A020",
    website: "https://simbg.pu.go.id",
    websiteLabel: "simbg.pu.go.id",
    services: ["pbg"],
    serviceLabels: ["PBG & SLF Gedung"],
  },
  {
    id: "klh",
    initials: "KLH",
    name: "Kementerian KLH",
    fullName: "Kementerian Lingkungan Hidup RI",
    role: "AMDAL, UKL-UPL & kepatuhan lingkungan",
    desc: "Dokumen Lingkungan Hidup adalah pintu masuk izin berusaha berisiko tinggi. Kami susun UKL-UPL dan AMDAL penuh — kajian teknis, pertemuan komisi pembahas, sampai persetujuan lingkungan terbit di Amdalnet.",
    color: "#00897B",
    website: "https://klhk.go.id",
    websiteLabel: "klhk.go.id",
    services: ["lingkungan", "b3-proper"],
    serviceLabels: ["AMDAL & UKL-UPL", "Limbah B3 & PROPER"],
  },
  {
    id: "kemenperin",
    initials: "PERIN",
    name: "Kemenperin",
    fullName: "Kementerian Perindustrian RI",
    role: "Standar industri, SNI & fasilitasi IKM",
    desc: "SNI produk industri, izin/registrasi industri, sampai fasilitasi IKM kami olah lewat kanal Kemenperin. Pabrik kami siap masuk supply chain korporat karena dokumen industri dan mutunya tertib sejak awal.",
    color: "#1565C0",
    website: "https://kemenperin.go.id",
    websiteLabel: "kemenperin.go.id",
    services: ["sni", "iso"],
    serviceLabels: ["SNI & SPPT-SNI", "ISO Manajemen"],
  },
  {
    id: "kemenparekraf",
    initials: "PRAK",
    name: "Kemenparekraf",
    fullName: "Kementerian Pariwisata dan Ekonomi Kreatif RI",
    role: "Tanda daftar angkutan wisata & ekonomi kreatif",
    desc: "Usaha pariwisata — dari armada wisata, TDAU, sampai kemitraan destinasi — kami kelola bersama Kemenparekraf dan Dishub terkait. Travel adventure klien kami legal mengantar wisatawan lintas provinsi.",
    color: "#D81B60",
    website: "https://kemenparekraf.go.id",
    websiteLabel: "kemenparekraf.go.id",
    services: ["pariwisata"],
    serviceLabels: ["Izin Pariwisata & TDAU"],
  },
  {
    id: "iata",
    initials: "IATA",
    name: "IATA",
    fullName: "International Air Transport Association",
    role: "Registrasi agen tiket global",
    desc: "Travel agent dengan registrasi IATA bisa menerbitkan tiket langsung dengan tarif agen — margin naik berlipat. Kami siapkan keuangan, sertifikasi personel, dan aplikasi ke IATA Kawasan Asia Pasifik hingga disetujui.",
    color: "#004E8C",
    website: "https://www.iata.org",
    websiteLabel: "iata.org",
    services: ["iata"],
    serviceLabels: ["Registrasi IATA"],
  },
  {
    id: "misa",
    initials: "MISA",
    name: "MISA Arab Saudi",
    fullName: "Ministry of Investment — Kingdom of Saudi Arabia",
    role: "Lisensi investasi asing Arab Saudi",
    desc: "Ekspansi usaha Indonesia ke Arab Saudi dimulai dari lisensi MISA: entitas 100% asing di sektor terbuka, alamat terdaftar, dan kepatuhan Saudization. Kami koordinasi lintas negara sampai lisensi Anda terbit dan entitas berdiri.",
    color: "#0B6E4F",
    website: "https://misa.gov.sa",
    websiteLabel: "misa.gov.sa",
    services: ["saudi-arabia"],
    serviceLabels: ["Lisensi MISA & Usaha Saudi"],
  },
  {
    id: "kemenlu",
    initials: "KLU",
    name: "Kemenlu",
    fullName: "Kementerian Luar Negeri RI",
    role: "Paspor, legalisasi dokumen & KBRI/KJRI",
    desc: "Paspor PMI, legalisasi dokumen perusahaan untuk luar negeri, sampai eskalasi perlindungan lewat KBRI/KJRI — kanal diplomatik yang kami kelola untuk klien yang bergerak lintas negara.",
    color: "#1F618D",
    website: "https://kemlu.go.id",
    websiteLabel: "kemlu.go.id",
    services: ["dokumen-pmi", "kontrak-visa-pmi"],
    serviceLabels: ["Dokumen & Paspor PMI", "Kontrak & Visa PMI"],
  },
  {
    id: "komdigi",
    initials: "KDG",
    name: "Komdigi",
    fullName: "Kementerian Komunikasi dan Digital RI",
    role: "PSE & legalitas platform digital",
    desc: "Platform, aplikasi, dan e-commerce wajib terdaftar sebagai Penyelenggara Sistem Elektronik (PSE) lokal/asing di Komdigi. Startup dan digital agency kami aman dari blokir karena legalitas digitalnya tertib.",
    color: "#7B1FA2",
    website: "https://komdigi.go.id",
    websiteLabel: "komdigi.go.id",
    services: ["pse-komdigi", "pendidikan"],
    serviceLabels: ["PSE Komdigi", "Izin Pendidikan"],
  },
];

/** Seal badge: size dalam px */
export type SealSize = "sm" | "md" | "lg";

export const SEAL_SIZES: Record<SealSize, number> = { sm: 44, md: 64, lg: 88 };

/** Hitung jumlah chip layanan total (untuk stat) */
export const TOTAL_INSTITUTION_SERVICES = INSTITUTIONS.reduce(
  (acc, i) => acc + i.services.length,
  0
);
