// ============================================================
// PUSATPERIZINAN.COM — Data Master Layanan & Konten
// Single source of truth untuk seluruh landing page
// ============================================================

import {
  FileCheck,
  Building2,
  Store,
  Scale,
  Leaf,
  FlaskConical,
  ShieldCheck,
  Plane,
  HardHat,
  HeartPulse,
  Truck,
  Coins,
  MoonStar,
  Landmark,
  PlaneTakeoff,
  Globe2,
  Pickaxe,
  UserRound,
  HandHeart,
  Fingerprint,
  Lightbulb,
  Ship,
  Barcode,
  BadgeCheck,
  ShieldPlus,
  UserCog,
  Stethoscope,
  GraduationCap,
  MonitorSmartphone,
  ClipboardCheck,
  Recycle,
  Rocket,
  type LucideIcon,
} from "lucide-react";

export interface ServiceItem {
  id: string;
  title: string;
  desc: string;
  icon: LucideIcon;
  price: string;
  duration: string;
  popular?: boolean;
  features: string[];
}

export const SERVICES: ServiceItem[] = [
  {
    id: "nib",
    title: "NIB & OSS-RBA",
    desc: "Nomor Induk Berusaha via OSS. Fondasi legal semua usaha — proses cepat, resmi pemerintah.",
    icon: FileCheck,
    price: "Rp 350rb",
    duration: "1 hari kerja",
    popular: true,
    features: ["Pendaftaran NIB resmi", "Konsultasi KBLI terbaik", "Sertifikat Standar sesuai risiko", "Panduan kewajiban pasca-terbit"],
  },
  {
    id: "pt",
    title: "Pendirian PT & PMA",
    desc: "Badan usaha paling kredibel untuk investasi, tender, dan skala besar. Akta resmi + SK Kemenkumham.",
    icon: Building2,
    price: "Rp 3,5jt",
    duration: "3-7 hari kerja",
    popular: true,
    features: ["Akta notaris + SK Kemenkumham", "NPWP badan & NIB", "Konsultasi struktur saham", "Domisili virtual opsional"],
  },
  {
    id: "cv",
    title: "Pendirian CV & Firma",
    desc: "Ideal untuk UMKM yang siap naik kelas. Murah, cepat, dan diakui lembaga keuangan.",
    icon: Store,
    price: "Rp 1,5jt",
    duration: "2-3 hari kerja",
    features: ["Akta notaris resmi", "NPWP & NIB", "Surat Keterangan Domisili", "Konsultasi perjanjian kerja sama"],
  },
  {
    id: "halal",
    title: "Sertifikasi Halal",
    desc: "Wajib bagi produk F&B (UU JPH). Proses via SEHATI — kami urus sampai label halal terbit.",
    icon: Leaf,
    price: "Rp 1,2jt",
    duration: "14-30 hari",
    features: ["Pendampingan Proses Produk (PPP)", "Koordinasi LPPOM & BPJPH", "Pemeriksaan bahan & dokumen", "Gratis subsidi kuota UMKM"],
  },
  {
    id: "bpom",
    title: "Izin Edar BPOM & PIRT",
    desc: "Jualan produk legally di marketplace & toko. MD untuk suplemen, PIRT untuk makanan olahan.",
    icon: FlaskConical,
    price: "Rp 2,5jt",
    duration: "30-60 hari",
    features: ["Pendaftaran CPPOB/MD", "Uji lab terhubung", "Desain label sesuai regulasi", "Pendampingan audit fasilitas"],
  },
  {
    id: "pbg",
    title: "PBG & SLF",
    desc: "Persetujuan Bangunan Gedung + Sertifikat Laik Fungsi — syarat buka usaha berbasis lokasi.",
    icon: HardHat,
    price: "Rp 2jt",
    duration: "14-30 hari",
    features: ["Pengukuran & gambar teknis", "Pengurusan ke DPMPTSP", "Checklist keselamatan", "SLF untuk bangunan existing"],
  },
  {
    id: "lingkungan",
    title: "Izin Lingkungan (AMDAL/UKL-UPL)",
    desc: "Legalitas lingkungan sesuai PP 22/2021 — penting untuk pabrik, tambang, dan konstruksi.",
    icon: ShieldCheck,
    price: "Rp 7,5jt",
    duration: "30-90 hari",
    features: ["Penyusunan dokumen lingkungan", "SPPL / UKL-UPL / AMDAL", "Koordinasi forum teknis", "Pendampingan matriks RKL-RPL"],
  },
  {
    id: "sni",
    title: "SNI & Sertifikasi Mutu",
    desc: "Standar nasional produk — buka akses tender dan kepercayaan pasar modern.",
    icon: Scale,
    price: "Rp 5jt",
    duration: "60-90 hari",
    features: ["Pemilihan SNI sesuai KBLI", "Persiapan audit LSPro", "Uji sampel lab terakreditasi", "Perbaikan dokumen mutu"],
  },
  {
    id: "pariwisata",
    title: "Izin Pariwisata & Hotel",
    desc: "TDAU, Sertifikat Usaha Pariwisata, hingga pendirian travel & wisata bahari.",
    icon: Plane,
    price: "Rp 2,5jt",
    duration: "14-21 hari",
    features: ["Tanda Daftar Usaha Pariwisata", "Sertifikasi usaha travel", "Izin wisata khusus", "Konsultasi BHP & gaya hidup halal"],
  },
  {
    id: "kesehatan",
    title: "Izin Klinik & Farmasi",
    desc: "SIPA, SIA, SIKIA hingga izin apotek — kami paham betul regulasi Kemenkes.",
    icon: HeartPulse,
    price: "Rp 7,5jt",
    duration: "30-60 hari",
    features: ["Izin usaha & izin praktik", "Koordinasi Dinkes & DPMPTSP", "Persyaratan sarana kesehatan", "NIB & sertifikat standar"],
  },
  {
    id: "logistik",
    title: "Izin Logistik & Angkutan",
    desc: "TDUP, Izin Niaga, hingga armada perizinan gudang & distribusi antar-pulau.",
    icon: Truck,
    price: "Rp 3,5jt",
    duration: "21-45 hari",
    features: ["TDUP & uji kelayakan armada", "Izin depot & gudang", "TPI & dokumen ekspor", "NIB sektor transportasi"],
  },
  {
    id: "tambang",
    title: "IUP / IUPK & Energi",
    desc: "Perizinan tambang, pengolahan, dan energi terbarukan bersama tim ahli komoditas.",
    icon: Coins,
    price: "Rp 25jt",
    duration: "90-180 hari",
    features: ["Penyusunan dokumen IUP/IUPK", "Koordinasi ESDM & Minerba", "RKAB & kewajiban pengusahaan", "Izin pengangkutan & penjualan"],
  },
  {
    id: "ppi-umroh",
    title: "Izin Umroh (PPIU)",
    desc: "Legalitas travel umroh resmi Kemenag: SIPU & SPPU via SIMPONI. Jamaah aman, travel naik kelas.",
    icon: MoonStar,
    price: "Rp 12jt",
    duration: "30-45 hari",
    popular: true,
    features: ["Pendirian PT + NIB sektor travel", "SPPU & SIPU ke Kemenag provinsi", "Pendaftaran SIMPONI / e-Katalog", "Rekening kolektif jamaah & kontrak maktab"],
  },
  {
    id: "ppi-haji",
    title: "Izin Haji (PPIH)",
    desc: "Puncak legalitas travel ibadah — izin PPIH Kemenag. Modal, dokumen & uji kelayakan kami pandu penuh.",
    icon: Landmark,
    price: "Rp 25jt",
    duration: "60-120 hari",
    features: ["Audit kelayakan modal & legalitas", "Pengajuan izin PPIH ke Kemenag", "Uji kelayakan & pembinaan Kemenag", "SK PPIH + penempatan PPUMI"],
  },
  {
    id: "iata",
    title: "Registrasi IATA",
    desc: "Akreditasi IATA untuk terbitkan tiket internasional resmi — standar global, akses BSP & komisi penuh.",
    icon: PlaneTakeoff,
    price: "Rp 10jt",
    duration: "45-90 hari",
    features: ["Konsultasi kriteria akreditasi IATA", "Bank guarantee & dokumen keuangan", "Registrasi IATA ID (Accredited/TIDS)", "Panduan BSP, CASS & settlement"],
  },
  {
    id: "saudi-arabia",
    title: "Izin Usaha Arab Saudi (MISA)",
    desc: "Ekspansi ke Arab Saudi era Vision 2030: lisensi MISA, CR & kepatuhan lokal — tim internasional kami.",
    icon: Globe2,
    price: "Rp 45jt",
    duration: "60-120 hari",
    features: ["Lisensi investasi MISA (100% asing)", "Commercial Registration (CR)", "Iqama GM, GOSI & Chamber of Commerce", "Kepatuhan ZATCA e-invoice & Saudization"],
  },
  {
    id: "rkab-tambang",
    title: "RKAB & Kepatuhan Tambang",
    desc: "RKAB 3 tahunan, perpanjangan IUP/IUPK, izin angkut & jual via MODI — kepatuhan penuh ESDM-Minerba.",
    icon: Pickaxe,
    price: "Rp 8jt",
    duration: "30-90 hari",
    features: ["Penyusunan RKAB 3 tahun + justifikasi", "Perpanjangan & regularisasi IUP/IUPK", "Izin angkut & penjualan via MODI", "LKPM minerba & good mining practice"],
  },
  {
    id: "pt-perorangan",
    title: "PT Perorangan (Cipta Kerja)",
    desc: "Badan usaha tanpa notaris via OSS — modal tanpa minimum, NIB sebagai identitas. Paling murah & tercepat untuk wirausaha.",
    icon: UserRound,
    price: "Rp 750rb",
    duration: "1-3 hari kerja",
    popular: true,
    features: ["100% online via OSS-RBA", "Modal tanpa minimum", "NIB = akta pendirian", "Konsultasi transisi ke PT biasa"],
  },
  {
    id: "koperasi-yayasan",
    title: "Koperasi, Yayasan & Perkumpulan",
    desc: "Badan hukum sosial & anggota: RKSM koperasi, akta yayasan, sampai SK Kemenkumham — lengkap dengan NPWP & NIB.",
    icon: HandHeart,
    price: "Rp 3,5jt",
    duration: "7-14 hari kerja",
    features: ["Akta notaris + SK Kemenkumham/Kemenkop", "Panduan AD/ART & RKSM", "NPWP & NIB terintegrasi", "Konsultasi tata kelola kelembagaan"],
  },
  {
    id: "merek",
    title: "Pendaftaran Merek (DJKI)",
    desc: "Lindungi brand Anda sebelum dibajak: cek ketersediaan, pengajuan online DJKI, perlindungan 10 tahun — per kelas Nice.",
    icon: Fingerprint,
    price: "Rp 900rb",
    duration: "6-12 bulan",
    popular: true,
    features: ["Cek ketersediaan & klasifikasi Nice", "Pengajuan online DJKI (PDKI)", "Perlindungan 10 tahun & perpanjangan", "Tanggapan keberatan & bukti pemakaian"],
  },
  {
    id: "paten-hki",
    title: "Paten, Hak Cipta & Desain Industri",
    desc: "Perlindungan invensi (20 tahun), paten sederhana, hak cipta karya & desain industri — draft klaim sampai substantif examination.",
    icon: Lightbulb,
    price: "Rp 2,5jt",
    duration: "1-24 bulan",
    features: ["Patent & paten sederhana (PNBP resmi)", "Hak cipta program/karya (tercepat 1-3 hari)", "Desain industri & rahasia dagang", "Lisensi & aksi pelanggaran HKI"],
  },
  {
    id: "api-impex",
    title: "API-U / API-P & Ekspor Impor",
    desc: "Angka Pengenal Impor-Ekspor via NIB, izin barang tertentu, sampai fasilitas PLB/KBN — buka pintu pasar global usaha Anda.",
    icon: Ship,
    price: "Rp 1,5jt",
    duration: "3-7 hari kerja",
    features: ["API-U (trading) & API-P (produsen) via OSS", "Izin L/S & barang tertentu", "Registrasi Insw & e-COO", "PLB / KBN untuk efisiensi kepabeanan"],
  },
  {
    id: "hscoo",
    title: "HS Code & COO (Form E/ATIGA)",
    desc: "Klasifikasi barang & Sertifikat Asal preferensi — nikmati tarif bea 0% via FTA/ATIGA dan hindari shipping hold di Bea Cukai.",
    icon: Barcode,
    price: "Rp 750rb",
    duration: "1-7 hari kerja",
    features: ["Analisis HS Code & risiko tarif", "COO preferensi: Form E, ATIGA, Form AI", "Registrasi Insw + e-COO", "Konsultasi klausul FTA yang berlaku"],
  },
  {
    id: "iso",
    title: "ISO 9001/14001/45001/22000",
    desc: "Sertifikasi sistem manajemen mutu, lingkungan, K3 & keamanan pangan via LS akreditasi KAN — syarat tender & buyer global.",
    icon: BadgeCheck,
    price: "Rp 12,5jt",
    duration: "60-90 hari",
    features: ["Gap analysis & penyusunan dokumen SMM", "Audit stage 1 & 2 LS akreditasi KAN", "Sertifikat 3 tahun + surveillance", "Pilihan skema: 9001/14001/45001/22000"],
  },
  {
    id: "smk3",
    title: "SMK3 & Kepatuhan K3",
    desc: "Sistem Manajemen Keselamatan Kesehatan Kerja (PP 50/2012) — wajib untuk perusahaan ≥100 pekerja atau berisiko tinggi, plus pembentukan P2K3.",
    icon: ShieldPlus,
    price: "Rp 7,5jt",
    duration: "30-60 hari",
    features: ["Audit SMK3 ke Disnaker/Kemnaker", "Penyusunan dokumen HIRARC & P2K3", "Sertifikasi ahli K3 umum", "Pengurusan SIO operator alat berat"],
  },
  {
    id: "rptka-kitas",
    title: "RPTKA, Notifikasi & KITAS Expatriat",
    desc: "Pekerja asing legal di perusahaan Anda: RPTKA, notifikasi (ex-IMTA), VITAS/KITAS index kerja, sampai KITAP & penanganan DKPTKA.",
    icon: UserCog,
    price: "Rp 3,5jt",
    duration: "7-14 hari kerja",
    popular: true,
    features: ["RPTKA temporer & permanen (Kemnaker)", "Notifikasi online + PNDP DKPTKA", "VITAS/KITAS index E23 kerja", "KITAP, alih status & EPO"],
  },
  {
    id: "alkes",
    title: "Izin Alkes & PKRT (AKL/AKD)",
    desc: "Izin edar alat kesehatan & perlengkapan PKRT: AKD lokal, AKL impor, IPAK distributor — semua kelas risiko A sampai D Kemenkes.",
    icon: Stethoscope,
    price: "Rp 3,5jt",
    duration: "45-90 hari",
    features: ["AKD (lokal) / AKL (impor) per kelas risiko", "IPAK untuk distributor alkes", "Pendampingan uji lab & teknis", "Pendaftaran e-Katalog & label Kemenkes"],
  },
  {
    id: "pendidikan",
    title: "Izin Lembaga Pendidikan & Kursus",
    desc: "Pendirian LKP/lembaga kursus & pelatihan: izin operasional, NPSN, sampai akreditasi BAN-PNF — siap serap program government.",
    icon: GraduationCap,
    price: "Rp 4jt",
    duration: "30-90 hari",
    features: ["Izin operasional Dinas Dikbud/Disnaker", "NPSN & sertifikat standar", "Akreditasi BAN-PNF / LALPK", "Kurikulum & struktur organisasi pandu"],
  },
  {
    id: "pse-komdigi",
    title: "PSE Komdigi (Digital Platform)",
    desc: "Tanda Daftar Penyelenggara Sistem Elektronik — wajib untuk website/aplikasi/OCR. Hindari pemblokiran & patuhi UU PDP.",
    icon: MonitorSmartphone,
    price: "Rp 2,5jt",
    duration: "7-21 hari",
    features: ["PSE ringan/berat & TD-PESE/TD-PDE", "Kepatuhan UU PDP (perlindungan data)", "Registrasi komdigi.go.id penuh", "Antisipasi pemblokiran & sanksi"],
  },
  {
    id: "lkpm",
    title: "LKPM & Kepatuhan OSS Tahunan",
    desc: "Laporan Kegiatan Penanaman Modal berkala (triwulan/semester/tahunan) — syarat perpanjangan izin & RPTKA, antisipasi pencabutan NIB.",
    icon: ClipboardCheck,
    price: "Rp 1,5jt",
    duration: "2-5 hari kerja",
    features: ["Susun & unggah LKPM via OSS", "Kalendar kewajiban otomatis", "Update data NIB & KBLI", "Penanganan sanksi administratif ringan"],
  },
  {
    id: "b3-proper",
    title: "Izin B3, TPS LB3 & PROPER",
    desc: "Pengelolaan limbah B3: izin simpan/angkut/olah, TPS LB3, PROPER biru-hijau-emas — kepatuhan lingkungan penuh KLHK/DLH.",
    icon: Recycle,
    price: "Rp 10jt",
    duration: "30-120 hari",
    features: ["Izin TPS LB3 & angkut B3", "PROPER biru/hijau/emas", "Persetujuan Lingkungan terintegrasi OSS", "Audit kinerja & dokumen RKL-RPL"],
  },
  {
    id: "ekspansi-asing",
    title: "Pendirian Entitas Luar Negeri",
    desc: "Ekspansi global: Pte Ltd Singapura, Sdn Bhd Malaysia, Free Zone Dubai, US LLC, Hong Kong, sampai Saudi MISA — bank account & compliance penuh.",
    icon: Rocket,
    price: "Rp 18jt",
    duration: "1 hari-8 minggu",
    features: ["Singapura, Malaysia, Dubai, US LLC, HK", "Registered address & nominee opsional", "Bank account opening support", "Kepatuhan tax residency & annual filing"],
  },
  {
    id: "kppa",
    title: "Kantor Perwakilan Asing (KPPA)",
    desc: "Hadir di Indonesia tanpa pendirian PT PMA — kantor perwakilan resmi via BKPM/OSS untuk riset pasar & koordinasi regional.",
    icon: Globe2,
    price: "Rp 12jt",
    duration: "2-3 minggu",
    features: ["Surat keputusan persetujuan BKPM", "Kartu identitas kantor perwakilan", "Panduan kewajiban pelaporan LKPM", "Jalur konversi ke PT PMA saat siap"],
  },
  {
    id: "bpjs",
    title: "BPJS Ketenagakerjaan & Kesehatan",
    desc: "Penuhi kewajiban ketenagakerjaan perusahaan: registrasi program JHT, JKK, JKM, JP & BPJS Kesehatan untuk seluruh karyawan.",
    icon: ShieldPlus,
    price: "Rp 900rb",
    duration: "3-5 hari kerja",
    features: ["Registrasi Badan Hukum & karyawan", "Perhitungan kontribusi & klasifikasi risiko", "Daftar ulang & mutasi karyawan", "Panduan kewajiban bulanan (JAMSOSTEK 2A)"],
  },
  {
    id: "higiene-sanitasi",
    title: "Sertifikat Higiene Sanitasi",
    desc: "Wajib bagi usaha makanan & minuman dari Dinas Kesehatan — restoran, kafe, katering, cloud kitchen, hingga kantin sekolah.",
    icon: ClipboardCheck,
    price: "Rp 1,5jt",
    duration: "1-2 minggu",
    features: ["Pemeriksaan sanitasi & higiene produksi", "Pendampingan uji lab sesuai peraturan Kemenkes", "Sertifikat resmi Dinkes setempat", "Panduan pelaporan berkala & perpanjangan"],
  },
  {
    id: "reklame",
    title: "Izin Terbit Reklame",
    desc: "Pasang billboard, videotron, banner, atau neon box secara legal — sesuai perda & retribusi daerah setempat.",
    icon: Lightbulb,
    price: "Rp 2,5jt",
    duration: "1-3 minggu",
    features: ["Izin terbit dari Bapenda/Dispenda", "Perhitungan retribusi & lokasi legal", "Perpanjangan & perubahan materi reklame", "Penanganan reklame politis & komersial"],
  },
];

export const PROCESS_STEPS = [
  {
    step: 1,
    title: "Konsultasi Gratis",
    desc: "Ceritakan usaha Anda via WA atau AI Consultant kami. Dalam 15 menit, Anda tahu persis izin apa yang dibutuhkan.",
  },
  {
    step: 2,
    title: "Penawaran & Roadmap",
    desc: "Kirim dokumen via foto. Kami susun roadmap perizinan lengkap dengan estimasi waktu & biaya transparan.",
  },
  {
    step: 3,
    title: "Kami yang Proses",
    desc: "Tim ahli kami urus semua koordinasi notaris, instansi, hingga revisi dokumen. Anda pantau progres real-time.",
  },
  {
    step: 4,
    title: "Izin Terbit, Bisnis Jalan",
    desc: "Dokumen resmi dikirim ke tangan Anda + panduan kewajiban pasca-terbit. Garansi uang kembali 100%.",
  },
];

export const PRICING = [
  {
    name: "UMKM",
    tagline: "Untuk usaha yang baru memulai",
    price: "Rp 350rb",
    period: "paket mulai dari",
    highlight: false,
    features: [
      "NIB + Sertifikat Standar (OSS-RBA)",
      "Konsultasi KBLI terbaik untuk modal & pajak",
      "NPWP usaha",
      "Panduan LKPM & kewajiban pajak",
      "Support WhatsApp 30 hari",
    ],
    cta: "Mulai dari Sini",
  },
  {
    name: "Bisnis",
    tagline: "Untuk usaha yang siap tumbuh",
    price: "Rp 3,5jt",
    period: "paket mulai dari",
    highlight: true,
    features: [
      "Semua fitur paket UMKM",
      "Pendirian PT / CV lengkap (akta + SK Kemenkumham)",
      "Sertifikasi Halal atau PIRT",
      "PBG & SLF untuk kantor/toko",
      "Prioritas proses — kurir dokumen",
      "Support WhatsApp 90 hari + laporan bulanan",
    ],
    cta: "Pilih Paket Bisnis",
  },
  {
    name: "Enterprise",
    tagline: "Untuk korporasi & investasi besar",
    price: "Rp 25jt",
    period: "paket mulai dari",
    highlight: false,
    features: [
      "Semua fitur paket Bisnis",
      "Izin Lingkungan (AMDAL/UKL-UPL)",
      "Perizinan sektor khusus (tambang, klinik, logistik)",
      "Pendirian PMA & struktur investasi asing",
      "Legal due diligence & compliance audit",
      "Account manager khusus + SLA kontrak",
    ],
    cta: "Konsultasi Enterprise",
  },
];

export const TESTIMONIALS = [
  {
    name: "Rina Kartika",
    role: "Owner, Dapur Rina Catering",
    city: "Bandung",
    rating: 5,
    content:
      "Sertifikat Halal yang tadinya bingung total, selesai 3 minggu. Timnya sabar banget ngajarin input SEHATI. Sekarang pesanan naik 40% karena label halal!",
  },
  {
    name: "Budi Santoso",
    role: "Direktur, BS Konstruksi",
    city: "Jakarta",
    rating: 5,
    content:
      "BUT, NIB, sampai SBU konstruksi semua dibantu. Yang paling saya suka: progres di-update tiap hari via WA. Tender pun lancar karena dokumen lengkap.",
  },
  {
    name: "Amelia Wijaya",
    role: "Founder, Skincare Ameera",
    city: "Surabaya",
    rating: 5,
    content:
      "BPOM produk skincare saya terbit dalam 45 hari. Mereka bantu sampai urusan label & klaim produk. Worth it banget untuk brand yang mau serius masuk marketplace.",
  },
  {
    name: "Hendra Gunawan",
    role: "Owner, HG Coffee House",
    city: "Yogyakarta",
    rating: 5,
    content:
      "Buka kafe pertama, bingung harus punya izin apa aja. Lewat fitur Cek Izin AI-nya langsung kelihatan 6 izin yang dibutuhkan. Paket Bisnis, 2 minggu beres semua.",
  },
  {
    name: "Siti Nurhaliza",
    role: "Pemilik, Batik Siti Store",
    city: "Solo",
    rating: 5,
    content:
      "Harga paling transparan dari semua yang saya tanya. NIB cuma sehari dan GRATIS konsultasi pajak UMKM-nya. Recommended untuk ibu-ibu pebisnis!",
  },
  {
    name: "Daniel Prasetyo",
    role: "CEO, TourJava Travel",
    city: "Bali",
    rating: 5,
    content:
      "Pindah dari konsultan lama karena prosesnya lama banget. Di sini TDAU & izin pariwisata selesai 12 hari. Sekarang kami jadi pelanggan repeat untuk 3 cabang.",
  },
];

export const FAQS = [
  {
    q: "Apakah prosesnya 100% legal dan aman?",
    a: "Mutlak legal. Kami bekerja sama dengan notaris resmi dan hanya menggunakan jalur resmi pemerintah (OSS-RBA, Kemenkumham, DPMPTSP, dsb). Semua dokumen terbit atas nama Anda dan dapat diverifikasi langsung di instansi. Kami juga memberikan garansi uang kembali 100% jika izin gagal terbit karena kesalahan proses kami.",
  },
  {
    q: "Berapa lama proses pengurusan izin?",
    a: "Tergantung jenis izin: NIB bisa selesai 1 hari kerja, pendirian PT/CV 3-7 hari kerja, Sertifikasi Halal 14-30 hari, BPOM 30-60 hari, dan AMDAL 30-90 hari. Saat konsultasi gratis, Anda akan mendapat estimasi waktu yang jelas per jenis izin sebelum memutuskan.",
  },
  {
    q: "Saya belum punya badan usaha, bisa diuruskan sekaligus?",
    a: "Sangat bisa — justru ini paket paling sering diambil. Kami urus dari pendirian badan usaha (PT/CV/Perseorangan), NIB, sampai izin operasional sektoral dalam satu roadmap. Anda tinggal siapkan KTP dan NPWP pribadi, sisanya kami yang koordinasi.",
  },
  {
    q: "Apakah saya harus datang ke kantor?",
    a: "Tidak perlu. 95% proses kami lakukan secara daring + kurir dokumen ke alamat Anda. Layanan kami menjangkau seluruh 38 provinsi dan 514 kabupaten/kota Indonesia. Untuk kebutuhan khusus (audit fisik, AMDAL, sektor tambang), tim kami yang akan datang ke lokasi Anda.",
  },
  {
    q: "Bisakah diurus izin travel umroh, haji, atau registrasi IATA?",
    a: "Bisa — kami punya divisi khusus Travel Ibadah & Aviasi. Kami urus pendirian PT travel, SIPU/SPPU (PPIU) sampai izin PPIH untuk haji, termasuk pendaftaran SIMPONI & rekening kolektif jamaah. Untuk agen tiket, kami siapkan akreditasi IATA (BSP/CASS) agar Anda bisa terbitkan tiket internasional resmi.",
  },
  {
    q: "Apakah bisa bantu buka usaha di Arab Saudi?",
    a: "Bisa. Tim internasional kami menangani ekspansi ke Arab Saudi era Vision 2030: lisensi investasi MISA (banyak sektor kini terbuka 100% kepemilikan asing), Commercial Registration (CR), Iqama direksi, sampai kepatuhan ZATCA e-invoice & Saudization. Semua dari Jakarta, tanpa Anda harus bolak-balik ke Riyadh.",
  },
  {
    q: "Bagaimana sistem pembayarannya?",
    a: "Transparan dan aman: 50% di awal (down payment), 50% setelah izin terbit. Pembayaran via transfer bank resmi atas nama badan hukum kami, lengkap dengan invoice & kontrak kerja sama. Tidak ada biaya tersembunyi — semua tercantum di penawaran resmi.",
  },
  {
    q: "Izin saya sudah kadaluarsa / belum pernah dilaporkan (LKPM), bisa dibantu?",
    a: "Bisa. Kami menangani regularisasi: perpanjangan izin, kewajiban LKPM di OSS, update data NIB, sampai penyelesaian sanksi administratif ringan. Konsultasikan kondisi Anda — semakin cepat dirapikan, semakin kecil risikonya.",
  },
];

export const SECTORS = [
  "Kuliner / F&B",
  "Retail / Toko",
  "Konstruksi / Properti",
  "Manufaktur / Pabrik",
  "Jasa / Konsultan",
  "Logistik / Transportasi",
  "Kesehatan / Klinik",
  "Pariwisata / Hotel",
  "Travel Ibadah (Haji/Umroh)",
  "Pendidikan",
  "Pertanian / Perkebunan",
  "Tambang / Energi",
  "Digital / Startup",
  "Lainnya",
];

export const WHATSAPP_NUMBER = "6281269999910"; // Nomor WA bisnis (official pusatperizinan.com)
export const WHATSAPP_DISPLAY = "0812-6999-9910";
export const OFFICE_NAME = "PusatPerizinan.com — Kantor Pusat SCBD";
export const OFFICE_ADDRESS = "Indonesia Stock Exchange Building, Tower 2, Lantai 5, SCBD Lot 13, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan 12190";
export const OFFICE_SHORT = "SCBD Lot 13, Jl. Jend. Sudirman Kav. 52-53, Jakarta Selatan 12190";
