// ============================================================
// PUSATPERIZINAN.COM — Detail Kaya Layanan Perizinan
// 19 layanan ditulis manual + 13 layanan memakai PERMIT_GUIDES
// Sumber: UU Cipta Kerja, PP 5/2021, PP 8/2025, riset 2025
// ============================================================

import type { ServiceDetail } from "./types";

/** Detail manual untuk layanan yang BELUM ada di PERMIT_GUIDES (seo-content.ts) */
export const LICENSE_DETAILS: ServiceDetail[] = [
  {
    id: "pt-perorangan",
    long: "PT Perorangan adalah bentuk badan usaha baru yang lahir dari UU Cipta Kerja — didirikan tanpa notaris, tanpa minimum modal, dan 100% online melalui OSS-RBA. NIB-nya berlaku sebagai akta pendirian sekaligus identitas badan usaha, sehingga pemilik tunggal bisa memiliki badan usaha formal dalam hitungan jam. Bentuk ini paling ideal untuk wirausaha solo, pemilik online shop, freelancer profesional, dan UMKM yang ingin naik kelas tanpa biaya notaris.",
    audience: ["Individu", "UMKM", "Online Shop"],
    legalBasis: "UU Cipta Kerja (UU 11/2020), PP 7/2021, Peraturan OSS",
    authority: "OSS-RBA (Kementerian Investasi/BKPM)",
    requirements: [
      "KTP & NPWP pribadi (NIK berNPWP aktif)",
      "Email & nomor HP yang belum terdaftar OSS",
      "Alamat usaha & kode pos",
      "Pemilihan KBLI usaha (maks 5 untuk 1 persetujuan)",
      "Pemegang saham tunggal (maksimal 1 orang)",
    ],
    steps: [
      "Konsultasi pemilihan KBLI & struktur usaha yang optimal untuk pajak",
      "Verifikasi dokumen & aktivasi akun OSS-RBA atas nama Anda",
      "Pengajuan PT Perorangan dengan pernyataan mandiri digital",
      "NIB terbit (berlaku sebagai akta pendirian + NPWP usaha)",
      "Panduan kewajiban pasca-terbit: LKPM & pajak UMKM 0,5%",
    ],
    faq: [
      { q: "Apa bedanya PT Perorangan dengan NIB perseorangan biasa?", a: "PT Perorangan adalah badan usaha resmi dengan NIB yang berlaku sebagai akta pendirian — statusnya lebih kuat saat mengajukan kredit bank, tender, atau kerja sama B2B dibanding NIB perseorangan. Keduanya bisa dikelola via OSS, tapi profil hukumnya berbeda. Tim kami bantu pilih yang paling menguntungkan untuk kondisi Anda." },
      { q: "Apakah PT Perorangan bisa pindah ke PT biasa nanti?", a: "Bisa. Ketika usaha bertumbuh dan butuh investor atau pemegang saham tambahan, kami pandu proses konversi: pendirian PT melalui notaris, alih aset, hingga pembatalan PT Perorangan yang rapi agar tidak bermasalah dengan pajak." },
      { q: "Berapa pajak PT Perorangan?", a: "Umumnya menggunakan skema PPh final 0,5% dari omzet selama omzet ≤ Rp4,8 miliar/tahun (gabungan usaha orang pribadi). Ini jauh lebih ringan daripada tarif umum PPh badan 22%. Kami juga bantu laporan SPT-nya sekaligus." },
    ],
    keywords: ["pt perorangan", "pendirian pt perorangan online", "nib pt perorangan", "usaha tanpa notaris", "badan usaha orang pribadi"],
  },
  {
    id: "koperasi-yayasan",
    long: "Koperasi, yayasan, dan perkumpulan adalah badan hukum dengan karakter sosial atau keanggotaan — masing-masing punya regulasi, kelembagaan, dan pajak berbeda. Kami urus dari akta notaris, SK Kemenkumham (yayasan/perkumpulan) atau RKSM & Badan Hukum KemenkopUKM (koperasi), sampai NPWP, NIB, dan panduan tata kelola agar lembaga Anda berjalan patuh sejak hari pertama.",
    audience: ["Komunitas", "Koperasi", "Yayasan", "Organisasi"],
    legalBasis: "UU 25/1992 (Koperasi), UU 16/2001 & UU 28/2004 (Yayasan), UU Cipta Kerja",
    authority: "Kemenkumham (AHU) & KemenkopUKM (SM-Online)",
    requirements: [
      "Nama lembaga + tujuan pendirian yang jelas",
      "Data KTP & NPWP para pendiri/pengurus/pembina",
      "Rapat pendirian (berita acara) & keputusan AD/ART",
      "Modal awal (koperasi: simpanan pokok & wajib anggota)",
      "Alamat kantor/kedudukan lembaga",
    ],
    steps: [
      "Konsultasi pemilihan bentuk: koperasi, yayasan, atau perkumpulan",
      "Penyusunan AD/ART yang tepat sesuai aktivitas lembaga",
      "Akta notaris + pengajuan SK Kemenkumham / RKSM Kemenkop",
      "Penerbitan NPWP & NIB lembaga",
      "Panduan laporan tahunan & kewajiban pajak lembaga",
    ],
    faq: [
      { q: "Apakah koperasi bebas pajak?", a: "Tidak sepenuhnya. Koperasi dikenakan PPh final 10% atas SHU yang dibagikan ke anggota, dan pajak lain sesuai kegiatannya. Namun ada banyak keringanan — kami pandu struktur agar koperasi Anda hemat pajak secara legal." },
      { q: "Yayasan atau perkumpulan lebih cocok untuk komunitas kami?", a: "Yayasan cocok untuk kegiatan sosial tanpa dibagi ke anggota (pendidikan, amal). Perkumpulan cocok bila ada perwakilan anggota dan kegiatan bersama. Kami bedah tujuan Anda lalu rekomendasikan bentuk terbaik — termasuk implikasi pajaknya." },
      { q: "Berapa lama proses hingga SK terbit?", a: "Umumnya 7-14 hari kerja: akta notaris 1-2 hari, SK Kemenkumham via AHU Online 3-7 hari, atau RKSM Kemenkop sesuai antrean daerah. Semua bisa dipantau statusnya oleh Anda." },
    ],
    keywords: ["pendirian koperasi", "pendirian yayasan", "sk kemenkumham yayasan", "badan hukum koperasi", "rksm koperasi"],
  },
  {
    id: "sni",
    long: "SNI (Standar Nasional Indonesia) adalah kunci masuk pasar formal: sektor tertentu (petir, helm, baja, kabel, galon, dll) wajib SNI, sementara sektor lain memakainya sebagai alasan pembeda di tender dan toko modern. Prosesnya mencakup pemilihan LSPro terakreditasi KAN, audit fasilitas produksi, uji lab sampel, hingga terbit sertifikat 4 tahun. Kami pandu setiap tahap supaya tidak gagal audit dan tidak buang biaya uji dua kali.",
    audience: ["Produsen", "UMKM", "Perusahaan"],
    legalBasis: "UU 7/2014 (Perindustrian), Permenperin terkait LSPro, SPPT SNI",
    authority: "BSN (Badan Standardisasi Nasional) via LSPro terakreditasi KAN",
    requirements: [
      "NIB & akta badan usaha aktif",
      "Fasilitas produksi siap audit (dokumen mutu, prosedur SOP)",
      "Sampel produk untuk uji lab terakreditasi",
      "Personel yang bertanggung jawab pada mutu",
      "KBLI & jenis produk sesuai kategori SNI yang diajukan",
    ],
    steps: [
      "Identifikasi SNI yang relevan dengan KBLI & produk Anda",
      "Gap analysis kesiapan pabrik & dokumen sistem mutu",
      "Pengajuan ke LSPro + jadwal audit pabrik",
      "Pengambilan & pengujian sampel di lab terakreditasi KAN",
      "Terbit sertifikat SPPT SNI (berlaku 4 tahun) + panduan surveilans",
    ],
    faq: [
      { q: "Produk apa saja yang wajib SNI?", a: "Lima puluh lebih kelompok produk wajib SNI menurut Permenperin: helm, ban, kabel, galon air, baja, minim said kit, kaca, dsb. Sisanya sukarela namun sangat membantu di marketplace & tender. Kirim nama produk Anda — kami cek status kewajibannya gratis." },
      { q: "Berapa biaya total sertifikasi SNI?", a: "Biaya resmi: uji lab (Rp2-15 juta tergantung produk), audit LSPro, dan PNBP. Total kebutuhan pemohon biasanya Rp5-25 juta tergantung jenis produk. Kami beri rincian transparan di penawaran sebelum mulai." },
      { q: "Berapa lama sertifikat SNI berlaku?", a: "Sertifikat SPPT SNI berlaku 4 tahun dengan surveilans berkala (biasanya tiap 6-12 bulan). Kami pandu juga proses surveilans & perpanjangan agar sertifikat tidak menggantung." },
    ],
    keywords: ["sertifikasi sni", "biaya sni", "lspro sni", "sni wajib produk", "cara mendapatkan sni"],
  },
  {
    id: "pariwisata",
    long: "Usaha pariwisata Indonesia diatur berlapis: NIB via OSS, Tanda Daftar Usaha Pariwisata (TDAU) sesuai kategori usaha (biro perjalanan, hotel, restoran, daya tarik wisata), sampai sertifikasi kelembagaan. Untuk travel umroh ada lapisan tambahan PPIU-PPIH Kemenag; untuk wisata bahari & kapal ada izin khusus. Kami petakan kebutuhan persis sesuai model bisnis Anda agar legal penuh tanpa izin mubazir.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "UU 10/2009 (Kepariwisataan), Permenparekraf kategori TDAU, PP 22/2021",
    authority: "OSS-RBA + Dinas Pariwisata / Kemenparekraf",
    requirements: [
      "NIB usaha dengan KBLI pariwisata yang tepat",
      "Akta & SK badan usaha (PT/CV)",
      "Pengurus dengan kualifikasi pariwisata (bila diminta)",
      "Dokumen sarana: akomodasi, armada, atau paket wisata",
      "Untuk hotel: PBG & SLF lokasi",
    ],
    steps: [
      "Konsultasi model bisnis → pemetaan izin wajib & opsional",
      "Penerbitan NIB + Sertifikat Standar sektor pariwisata",
      "Pengajuan TDAU ke Dinas Pariwisata setempat",
      "Pelengkap: PBG/SLF, sertifikasi bintang hotel, izin wisata khusus",
      "Panduan kewajiban laporan pariwisata & pajak daerah",
    ],
    faq: [
      { q: "Apa itu TDAU dan apakah wajib?", a: "TDAU (Tanda Daftar Usaha Pariwisata) adalah legalitas khusus usaha pariwisata yang diterbitkan dinas pariwisata setempat. Wajib bagi hotel, biro perjalanan, restoran (kategori tertentu), dan daya tarik wisata. Tanpa TDAU, usaha Anda bisa dianggap ilegal saat inspeksi." },
      { q: "Usaha villa/homestay perlu izin apa?", a: "Setidaknya NIB + TDAU kategori akomodasi (villa/homestay), PBG & SLF bangunan, dan patuhi pajak daerah (PBJT, pajak hotel). Di Bali/NTB ada aturan zona & status tanah yang penting dicek sebelum investasi — kami bantu due diligence." },
      { q: "Apa beda izin travel biasa dan travel umroh?", a: "Travel wisata biasa cukup NIB + TDAU biro perjalanan wisata. Travel umroh/haji harus memiliki izin PPIU/PPIH dari Kemenag — jenjangnya jauh lebih tinggi (PT, modal, kapasitas jamaah). Kami urus keduanya, termasuk upgrade dari travel biasa ke PPIU." },
    ],
    keywords: ["izin pariwisata", "tdau", "izin usaha travel", "izin villa bali", "izin homestay"],
  },
  {
    id: "kesehatan",
    long: "Izin layanan kesehatan memerlukan dua lapis: izin usaha (NIB + Sertifikat Standar sektor kesehatan) dan izin teknis dari Dinkes — SIPA (apotek), SIA (klinik & praktik), SIKIA (praktik kedokteran gigi), serta izin laboratorium atau puskesmas bila relevan. Kami mahir koordinasi Dinkes & DPMPTSP, dari standar sarana (Bilik, alat, personel) hingga approval online e-SIPKes, sehingga klinik Anda buka tepat waktu tanpa revisi berulang.",
    audience: ["Dokter", "UMKM", "Perusahaan"],
    legalBasis: "UU 17/2023 (Kesehatan), PP 28/2024, Permenkes izin & standar sarana",
    authority: "Dinkes + DPMPTSP + Kemenkes (e-SIPKes / SATUSEHAT)",
    requirements: [
      "NIB usaha kesehatan + sertifikat standar",
      "SIP/SIUP dokter & tenaga kesehatan yang bertugas",
      "Standar sarana & prasarana sesuai Permenkes (ruang, alat)",
      "Dokumen legalitas gedung (PBG/SLF)",
      "Untuk apotek: SIPA apoteker & resep logistik",
    ],
    steps: [
      "Konsultasi jenis layanan → petakan izin wajib",
      "Penerbitan NIB + sertifikat standar kesehatan via OSS",
      "Penyusunan dokumen standar sarana & personel",
      "Pengajuan izin teknis Dinkes (SIPA/SIA/SIKIA) + verifikasi",
      "Integrasi SATUSEHAT & panduan kewajiban laporan rutin",
    ],
    faq: [
      { q: "Klinik kecil (praktik dokter) perlu PT atau cukup izin praktik?", a: "Praktik mandiri cukup SIP dari Dinkes tanpa PT. Klinik dengan berbagai layanan & tenaga biasanya butuh badan usaha (PT/CV) + izin klinik. Kami cek model bisnis Anda lalu susun roadmap yang hemat." },
      { q: "Berapa lama izin klinik terbit?", a: "30-60 hari tergantung kelengkapan sarana & antrean verifikasi Dinkes. Dengan persiapan dokumen yang rapi sejak awal, kami sering menyelesaikannya di rentang bawah. Verifikasi online e-SIPKes mempercepat banyak di kota besar." },
      { q: "Apakah sekolah keperawatan/tindakan estetika termasuk layanan kesehatan?", a: "Ya — klinik estetika, kecantikan medis, dan layanan medis lain diatur sama ketatnya (izin klinik + personel bersertifikat). Kegiatan tanpa izin bisa berujung operasi administratif & sanksi hukum. Konsultasikan dulu sebelum buka." },
    ],
    keywords: ["izin klinik", "sia dinkes", "izin apotek", "sipa", "izin usaha kesehatan"],
  },
  {
    id: "logistik",
    long: "Perizinan logistik menyentuh banyak titik: NIB sektor transportasi, TDUP (Tanda Daftar Usaha Perhubungan) untuk angkutan barang/orang, uji kelayakan armada (SRUT/SRUK), izin gudang & depot, hingga izin niaga barang untuk distribusi antar-pulau. Untuk operator pelabuhan, TPI, atau logistik lintas negara, ada izin tambahan yang bergantung skala & jalur operasi Anda. Kami mapkan semua supaya armada bergerak legal sejak hari pertama.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "UU 23/2014 (Perhubungan), PP 74/2014 (Angkutan Jalan), PP 22/2021",
    authority: "Dishub + DPMPTSP + Kemenhub",
    requirements: [
      "NIB dengan KBLI transportasi/distribusi",
      "Akta badan usaha & SK Kemenkumham",
      "Bukti kepemilikan/sewa armada + uji kelayakan (SRUT/SRUK)",
      "Dokumen gudang/depot (PBG, sewa, domisili)",
      "Untuk angkut barang tertentu: izin niaga & dokumen khusus",
    ],
    steps: [
      "Konsultasi skala & jenis operasi logistik Anda",
      "Penerbitan NIB + sertifikat standar sektor perhubungan",
      "Pengajuan TDUP ke Dishub + uji kelayakan armada",
      "Perizinan gudang/depot (PBG, SLF, izin lingkungan bila perlu)",
      "Panduan laporan armada & kepatuhan rutin Dishub",
    ],
    faq: [
      { q: "Ekspedisi online shop (kurir antar kota) perlu izin apa?", a: "Paling tidak NIB sektor pos/kurir + TDUP angkutan barang bila pakai armada sendiri. Jika bekerja sama dengan kurir mitra, ada kewajiban dokumen kemitraan yang berbeda. Ceritakan model operasinya — kami susun roadmap izinnya." },
      { q: "Gudang di kawasan industri, izinnya apa saja?", a: "NIB, PBG & SLF gudang, izin lingkungan (UKL-UPL tergantung skala), dan bila menyimpan barang tertentu (B3, migas) ada izin tambahan. Kami urus paket lengkap sekali jalan." },
      { q: "Berapa biaya perizinan logistik?", a: "Mulai Rp3,5 juta untuk paket TDUP + NIB + dokumen armada. Untuk kawasan operasi luas (gudang besar, armada >20 unit, TPI), biaya menyesuaikan. Kami beri penawaran detail setelah konsultasi gratis." },
    ],
    keywords: ["izin logistik", "tdup", "izin angkutan barang", "izin gudang", "izin distribusi"],
  },
  {
    id: "tambang",
    long: "Perizinan tambang (IUP/IUPK) adalah perizinan paling kompleks di Indonesia: kombinasi izin wilayah dari Pemda/ESDM, dokumen lingkungan (AMDAL), RKAB pengusahaan, hingga izin angkut & penjualan via MODI. Setiap komoditas dan wilayah punya prosedur berbeda, dan satu kesalahan dokumen bisa memakan waktu berbulan-bulan. Tim ahli komoditas kami (batubara, nikel, emas, mineral lain, geotermal) memandu dari survey awal hingga produksi.",
    audience: ["Perusahaan", "Investor"],
    legalBasis: "UU 3/2020 (Perubahan Minerba), PP 96/2021, Permen ESDM Minerba",
    authority: "ESDM (Ditjen Minerba) + DPMPTSP + KLHK",
    requirements: [
      "Badan usaha (PT) dengan KBLI tambang yang sesuai",
      "Dokumen lokasi & ketersediaan wilayah minerba",
      "Studi kelayakan & rencana teknik pengusahaan",
      "Dokumen lingkungan (AMDAL) + Persetujuan Lingkungan",
      "Kesiapan modal & rencana investasi (untuk uji kelayakan)",
    ],
    steps: [
      "Konsultasi komoditas & lokasi → strategi pengurusan",
      "Penyusunan dokumen IUP/IUPK + studi teknis",
      "Koordinasi ESDM/Pemda untuk approval wilayah",
      "AMDAL + Persetujuan Lingkungan terintegrasi OSS",
      "RKAB, izin angkut & penjualan via MODI → produksi",
    ],
    faq: [
      { q: "IUP dan IUPK bedanya apa?", a: "IUP (Izin Usaha Pertambangan) untuk penambangan reguler dengan izin wilayah. IUPK untuk KUB (kawasan usaha pertambangan) dan khusus IUPK untuk penerus kontrak karya/CCOW. Ketentuan modal, laporan, dan durasi berbeda — kami bantu pilih jalur yang benar." },
      { q: "Berapa lama proses IUP sampai bisa produksi?", a: "90-180 hari untuk izin dasar (tergantung wilayah & komoditas), lalu AMDAL 60-90 hari, RKAB & izin penjualan tambahan. Total umumnya 6-12 bulan hingga produksi pertama. Ada jalur percepatan bila dokumen sangat lengkap sejak awal." },
      { q: "Apakah wajib punya pabrik smelter?", a: "Untuk beberapa komoditas (nikel, bauksit, dll) ada kewajiban pengolahan & pemurnian (obligasi hilirisasi). Aturannya berbeda per mineral. Kami bantu kajian strategi: bangun smelter, gabung KKPK, atau skema lain yang legal." },
    ],
    keywords: ["iup tambang", "iupk", "izin tambang batubara", "izin nikel", "rkab tambang"],
  },
  {
    id: "merek",
    long: "Merek adalah aset tak berwujud paling bernilai untuk bisnis — terutama saat mulai dikenal pasar. Pendaftaran di DJKI (PDKI) memberikan hak eksklusif 10 tahun (dapat diperpanjang) untuk nama, logo, atau kombinasi Anda. Kami bantu cek ketersediaan terhadap ribuan merek terdaftar (hindari keberatan pihak ketiga), klasifikasi Nice yang tepat (per kelas barang/jasa), pengajuan online, hingga tanggapan bila ada keberatan atau pembuktian pemakaian.",
    audience: ["Individu", "UMKM", "Perusahaan"],
    legalBasis: "UU 20/2016 (Merek & Indikasi Geografis) + perubahannya",
    authority: "DJKI (Direktorat Jenderal Kekayaan Intelektual) — Kemenkumham",
    requirements: [
      "Nama/logo merek (file gambar resolusi baik bila ada)",
      "KTP/NPWP pemohon (individu) atau akta badan usaha",
      "Daftar barang/jasa yang dipakai merek (klasifikasi Nice)",
      "Contoh pemakaian merek (kemasan, website, social media)",
      "Surat kuasa (kami siapkan)",
    ],
    steps: [
      "Konsultasi & pengecekan ketersediaan merek di PDKI",
      "Penentuan kelas Nice yang tepat (maksimalkan perlindungan)",
      "Pengajuan online ke DJKI + bayar PNBP resmi",
      "Pemantauan: pengumuman 3 bulan & tanggapi keberatan (bila ada)",
      "Terbit sertifikat merek (10 tahun) + panduan pemakaian sah",
    ],
    faq: [
      { q: "Berapa lama merek terdaftar?", a: "Proses resmi DJKI sekitar 6-12 bulan (termasuk pengumuman 3 bulan untuk keberatan pihak ketiga). Hak Anda mulai berlaku sejak tanggal pengajuan, jadi sebaiknya ajukan sedini mungkin sebelum brand terlalu dikenal." },
      { q: "Apakah merek bisa didaftarkan sebelum usaha jalan?", a: "Bisa. Merek dapat diajukan oleh individu dengan rencana usaha — tak perlu menunggu NIB/PT jadi. Malah ini strategi bagus untuk amankan nama sebelum kompetitor atau pembajak merek menang lebih dulu." },
      { q: "Kena keberatan orang lain, apakah bisa bantu?", a: "Bisa. Kami bantu tanggapan keberatan (bukti pemakaian, argumen hukum), dan bila perlu negosiasi dengan pemberi keberatan. Tingkat keberhasilan tanggapan cukup tinggi bila Anda benar-benar memakai merek lebih dulu." },
    ],
    keywords: ["pendaftaran merek", "biaya daftar merek", "dki merek", "hak eksklusif merek", "merek per kelas nice"],
  },
  {
    id: "paten-hki",
    long: "Selain merek, HKI mencakup paten (invensi 20 tahun), paten sederhana (produk baru & aplikatif), hak cipta (karya kreatif, software, lagu — tercepat 1-3 hari), desain industri (tampilan visual produk), hingga rahasia dagang. Setiap jenis punya syarat & strategi berbeda: paten butuh kebaruan global & draft klaim kuat; hak cipta cukup bukti karya. Kami pandu pilih perlindungan paling tepat & ajukan dengan dokumen yang tahan uji.",
    audience: ["Individu", "UMKM", "Perusahaan"],
    legalBasis: "UU 13/2016 (Paten), UU 28/2014 (Hak Cipta), UU 31/2000 (Desain Industri)",
    authority: "DJKI — Kemenkumham",
    requirements: [
      "Deskripsi & dokumen invensi/karya (sketsa, kode, manuskrip)",
      "Identitas pemohon (KTP/NPWP atau akta badan usaha)",
      "Bukti kebaruan (untuk paten: pencarian prior art)",
      "Untuk desain industri: gambar teknis 6 sisi",
      "Surat kuasa & pengalihan hak (bila pemohon berbeda pencipta)",
    ],
    steps: [
      "Konsultasi jenis HKI & strategi perlindungan terbaik",
      "Penulisan draft klaim/deskripsi yang kuat (untuk paten)",
      "Pengajuan online DJKI + PNBP resmi per jenis",
      "Pemantauan proses substantif (paten) atau terbit cepat (cipta)",
      "Panduan lisensi, penjualan & penegakan hak HKI",
    ],
    faq: [
      { q: "Patennya bagus untuk produk saya atau cukup hak cipta?", a: "Paten cocok untuk teknologi/proses/alat yang baru & inventif; hak cipta untuk karya kreatif (software, musik, buku); desain industri untuk tampilan produk. Kami analisis produk Anda lalu rekomendasikan kombinasi perlindungan yang paling ekonomis dan kuat." },
      { q: "Berapa biaya paten di DJKI?", a: "PNBP paten resmi sekitar Rp1,5 juta (substantif) + biaya draft profesional. Paten sederhana lebih murah. Hak cipta dari ratusan ribu rupiah. Total tergantung kompleksitas — kami beri estimasi jelas di awal." },
      { q: "Karyaku sudah viral, masih bisa didaftarkan?", a: "Hak cipta tetap bisa didaftarkan (proteksi muncul otomatis sejak karya dibuat), tapi untuk paten, kebaruan bisa gugur bila sudah dipublikasikan. Segera konsultasi — kami bantu strategi pendaftaran retroaktif yang legal." },
    ],
    keywords: ["paten indonesia", "hak cipta karya", "desain industri", "biaya paten", "dki hki"],
  },
  {
    id: "api-impex",
    long: "API (Angka Pengenal Impor-Ekspor) adalah tiket masuk Anda ke dunia perdagangan internasional — terbit otomatis bersama NIB via OSS dengan jenis API-U (distributor/trader) atau API-P (produsen yang mengimpor bahan baku). Namun untuk barang lartas (tertentu) ada izin tambahan: PI (Persetujuan Impor), PE (Persetujuan Ekspor), registrasi Ins Customs, sampai fasilitas PLB/KBN untuk efisiensi pajak. Kami susun struktur impor-ekspor Anda yang legal & hemat.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "UU 17/2006 (Kepabeanan), PP 36/2023, Perpermadag lartas",
    authority: "OSS-RBA + Kemendag + Bea Cukai",
    requirements: [
      "NIB aktif dengan KBLI perdagangan/produsen",
      "Badan usaha atau perseorangan dengan NPWP",
      "Info barang yang akan diimpor/ekspor (HS Code)",
      "Dokumen kontrak/purchase order awal (bila ada)",
      "Untuk barang tertentu: izin khusus (BPOM, SNI, dll)",
    ],
    steps: [
      "Konsultasi model bisnis impor/ekspor & pemilihan API-U/API-P",
      "Penerbitan NIB + API via OSS (integrasi otomatis)",
      "Registrasi Ins Customs & penentuan HS Code yang tepat",
      "Perizinan lartas: PI/PE/izin barang tertentu sesuai komoditas",
      "Panduan dokumen kepabeanan & kewajiban laporan berkala",
    ],
    faq: [
      { q: "Apa beda API-U dan API-P?", a: "API-U untuk importer/eksporter distributor (barang jadi untuk dijual kembali). API-P untuk produsen yang mengimpor bahan baku/mesin untuk produksi. Salah pilih bisa berujung penolakan PI — kami bantu tentukan sesuai pola bisnis Anda." },
      { q: "Bisnis kecil online shop impor barang, perlu API?", a: "Untuk impor reguler via jalur udara/laut, ya — minimal API-U + NIB. Ada jalur impor kecil via kurir untuk nilai kecil, tapi berbatas nilai & berulang kali. Kami bantu pilih jalur legal paling ekonomis." },
      { q: "Barang saya kena lartas, harus punya izin tambahan?", a: "Iya, barang tertentu (pangan, elektronik, tekstil, bahan kimia, dll) butuh PI/PE dari Kementerian terkait + sering kali izin pendukung (BPOM, SNI, sertifikat halal). Kami petakan syaratnya per komoditas sebelum Anda impor supaya tidak stuck di pelabuhan." },
    ],
    keywords: ["api u", "api p", "izin impor", "izin ekspor", "pi kemendag"],
  },
  {
    id: "hscoo",
    long: "HS Code (Harmonized System) yang tepat menentukan besaran bea masuk, PPN, dan lartas — salah klasifikasi bisa berujung denda atau overpayment. COO (Certificate of Origin) preferensi seperti Form E (ASEAN-China), ATIGA (ASEAN), dan Form AI (ASEAN-India) memberi tarif 0% atau diskon besar bila syarat memenuhi aturan asal. Kami bantu analisis HS Code, tentukan FTA terbaik, dan urus COO agar kargo Anda bebas bea maksimal tanpa shipping hold di Bea Cukai.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "ATIGA, Perjanjian FTA Indonesia (ACFTA, AIFTA, IJEPA, CEPA)",
    authority: "Bea Cukai (DJBC) + Kemendag (COO preferensi)",
    requirements: [
      "Deskripsi detail barang (bahan, fungsi, komposisi)",
      "NIB/API aktif & akses CEISA (registrasi kami bantu)",
      "Invoice, packing list & dokumen pengangkutan",
      "Untuk COO: bukti asal barang (BOM, pabrik produksi)",
      "Formulir pernyataan asal barang (template kami sediakan)",
    ],
    steps: [
      "Analisis HS Code & risiko tarif berdasarkan spesifikasi barang",
      "Identifikasi FTA yang paling menguntungkan (ATIGA, Form E, dll)",
      "Registrasi CEISA / e-COO untuk akses sistem",
      "Pengajuan COO per shipment & panduan dokumen sumber",
      "Monitoring & konsultasi saat ada query Bea Cukai",
    ],
    faq: [
      { q: "HS Code salah bisa bagaimana?", a: "Konsekuensinya serius: tarif jadi salah (overpayment), atau lebih buruk — dianggap pelanggaran klasifikasi (denda hingga 1000% dari kekurangan bayar). Kami bantu audit HS Code Anda saat ini supaya aman & efisien." },
      { q: "Form E untuk impor dari China, apakah semuanya 0%?", a: "Tidak semua. Hanya item yang memenuhi aturan asal (ROO) dan tercantum di daftar preferensi ACFTA. Kami cek line-by-line — banyak produk yang bisa 0%, tapi ada juga yang tidak memenuhi syarat." },
      { q: "COO bisa diurus tanpa ke pelabuhan?", a: "Bisa. COO kini elektronik (e-COO) via CEISA/Insw — pengajuan online dengan dokumen digital. Kami pandu setup & prosesnya sekali agar Anda bisa self-service ke depan, atau kami urus penuh per shipment." },
    ],
    keywords: ["hs code", "coo form e", "atiga", "bea masuk 0 persen", "e-coo"],
  },
  {
    id: "iso",
    long: "Sertifikasi ISO membuka pintu tender, kerja sama BUMN/multinasional, dan kepercayaan buyer global. Yang paling dicari: ISO 9001 (mutu), 14001 (lingkungan), 45001 (K3), 22000 (keamanan pangan), 27001 (keamanan informasi), 37001 (anti-bribery), 50001 (energi). Prosesnya: gap analysis → penyusunan dokumen SMM → audit stage 1 & 2 oleh LS terakreditasi KAN → sertifikat 3 tahun dengan surveilans tahunan. Kami manajemen penuh agar audit pertama langsung lulus.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "Standar ISO International + akreditasi KAN (Komite Akreditasi Nasional)",
    authority: "Lembaga Sertifikasi (LS) terakreditasi KAN",
    requirements: [
      "NIB & badan usaha aktif",
      "Proses bisnis yang berjalan (operasional ≥3 bulan idealnya)",
      "Personel yang bisa ditunjuk (MR, tim mutu)",
      "Dokumen SOP/dokumen mutu (kami pandu susun)",
      "Kommitmen manajemen untuk audit & perbaikan",
    ],
    steps: [
      "Gap analysis kondisi perusahaan vs standar ISO terpilih",
      "Penyusunan manual mutu, SOP & dokumen pendukung",
      "Pelatihan internal audit & simulasi (mock audit)",
      "Audit stage 1 (dokumen) & stage 2 (lapangan) oleh LS",
      "Terbit sertifikat 3 tahun + panduan surveilans tahunan",
    ],
    faq: [
      { q: "ISO mana yang paling penting untuk perusahaan saya?", a: "Tergantung sektor & target pasar: kontraktor → ISO 9001 + 45001; pabrik pangan → 22000 + HACCP; software → 27001; ekspor Eropa → 14001. Kami bedah kebutuhan tender/buyer Anda lalu rekomendasikan kombinasi paling efektif." },
      { q: "Berapa biaya ISO untuk perusahaan kecil?", a: "Mulai Rp12,5 juta per standar (termasuk dokumen, audit, sertifikat) untuk perusahaan kecil dengan 1-2 lokasi. Untuk multi-situs atau beberapa standar sekaligus, ada integrasi sistem yang lebih hemat. Konsultasi gratis untuk penawaran presisi." },
      { q: "Berapa lama sampai sertifikat terbit?", a: "60-90 hari bila dokumen & operasional siap: 2-4 minggu penyusunan, 1-2 minggu audit, 1-2 minggu terbit. Untuk perusahaan yang sudah terorganisir baik, bisa lebih cepat. Kami kelola jadwal supaya tidak memperlambat tender Anda." },
    ],
    keywords: ["sertifikasi iso", "iso 9001", "iso 14001", "iso 45001", "lembaga sertifikasi kan"],
  },
  {
    id: "smk3",
    long: "SMK3 (Sistem Manajemen Keselamatan & Kesehatan Kerja) wajib bagi perusahaan dengan ≥100 pekerja atau berisiko tinggi (PP 50/2012) — tanpa SMK3, Anda bisa sanksi administratif & rentan gugatan K3. Prosesnya: pembentukan P2K3, audit internal, penyusunan dokumen HIRARC, sampai audit eksternal oleh Kemnaker/Disnaker dengan hasil 3 kategori (menengah/utama/emas). Bonus: sertifikat SMK3 adalah salah satu syarat tender konstruksi & proyek pemerintah.",
    audience: ["Perusahaan"],
    legalBasis: "PP 50/2012, Permenaker 26/2014, UU 1/1970 (K3)",
    authority: "Kemnaker / Disnaker (audit eksternal SMK3)",
    requirements: [
      "NIB & badan usaha dengan pekerja ≥100 ATAU berisiko tinggi",
      "Pembentukan P2K3 (SK + struktur tim)",
      "Penunjukan akuntan K3 (Ahli K3 Umum tersertifikasi)",
      "Dokumen K3: kebijakan, HIRARC, prosedur darurat, APD",
      "Rekaman kecelakaan kerja & laporan berkala",
    ],
    steps: [
      "Assessment kewajiban SMK3 (jumlah pekerja & risiko)",
      "Pembentukan P2K3 & penetapan akuntabilitas K3",
      "Penyusunan dokumen K3 + HIRARC & SOP keamanan",
      "Audit internal (self-assessment) + perbaikan gap",
      "Audit eksternal Kemnaker/Disnaker → terbit sertifikat SMK3",
    ],
    faq: [
      { q: "Perusahaan saya 60 orang, wajib SMK3?", a: "Bila berisiko tinggi (konstruksi, pabrik kimia, energi) — ya wajib. Bila risiko rendah dan <100 pekerja, SMK3 belum wajib tapi sangat dianjurkan (meningkatkan kredibilitas & mengurangi risiko hukum). Kami bantu kajian risiko gratis untuk memastikan." },
      { q: "Apa beda SMK3 dengan ISO 45001?", a: "SMK3 adalah kewajiban nasional (audit oleh Kemnaker/Disnaker), ISO 45001 standar internasional (audit LS terakreditasi). Perusahaan besar sering keduanya: SMK3 untuk patuh hukum Indonesia, ISO 45001 untuk kredibilitas global. Sistemnya bisa disatukan agar hemat." },
      { q: "Berapa lama audit SMK3?", a: "Audit eksternal biasanya 2-3 hari di lokasi setelah persiapan 30-60 hari (dokumen, P2K3, self-assessment). Sertifikat terbit beberapa minggu setelah lulus. Kami kelola seluruh proses termasuk penjadwalan auditor." },
    ],
    keywords: ["smk3", "sertifikat smk3", "p2k3", "audit smk3", "k3 perusahaan"],
  },
  {
    id: "rptka-kitas",
    long: "Merekrut tenaga kerja asing (TKA) memerlukan jenjang legal yang tepat: RPTKA (Rencana Penggunaan Tenaga Kerja Asing) dari Kemnaker sebagai fondasi, lalu Notifikasi kerja (pengganti IMTA), VITAS/KITAS index E23, DPKK (Dana Pendidikan Keterampilan) US$100/bulan/TKA, hingga kepatuhan DKPTKA. Untuk pasangan & keluarga ada KITAS dependent; untuk masa panjang ada KITAP. Kami urus keseluruhan — termasuk penanganan kompleks (alih status, perubahan pekerjaan, EPO) — agar perusahaan Anda tidak terancam sanksi imigrasi.",
    audience: ["Perusahaan"],
    legalBasis: "UU 6/2011 (Imigrasi), Permenaker 10/2018, PP 34/2021",
    authority: "Kemnaker (RPTKA) + Imigrasi (Kemenkumham)",
    requirements: [
      "PT/PMA dengan modal disetor memenuhi syarat (Rp10 miliar umumnya)",
      "Rencana posisi TKA: jabatan, durasi, alasan kebutuhan",
      "Data paspor TKA & dokumen pendukung (ijazah, pengalaman)",
      "Struktur karyawan Indonesia vs TKA (rasio 3:1 idealnya)",
      "NPWP perusahaan & NIB aktif",
    ],
    steps: [
      "Konsultasi posisi TKA & struktur kepatuhan perusahaan",
      "Pengajuan RPTKA ke Kemnaker (temporer/permanen)",
      "Pembayaran DPKK & terbit Notifikasi kerja",
      "VITAS (visa index E23) di KBRI/Embassy → kedatangan",
      "KITAS & KTP-orang asing, MERP, panduan kewajiban rutin",
    ],
    faq: [
      { q: "Berapa modal minimum PT untuk pegang TKA?", a: "Umumnya modal disetor ≥ Rp10 miliar (umum untuk semua kegiatan usaha). Ada pengecualian: perusahaan publik, kantor perwakilan, dan beberapa sektor dengan syarat berbeda. Kami cek kelayakan PT Anda gratis sebelum mulai." },
      { q: "Apa itu DPKK dan berapa nilainya?", a: "Dana Pendidikan Keterampilan & Kerja (DPKK) adalah kontribusi US$100/bulan/TKA dibayarkan ke Kemnaker sejak 2022 (menggantikan konsep IAS). Ini bagian dari kewajiban legal — kami hitung & proaktor pembayarannya sesuai jadwal." },
      { q: "Apakah pasangan & anak expatriat bisa ikut?", a: "Bisa — mereka dapat KITAS dependent (index E31-E33) berbasis status TKA utama. Tapi dependent tidak boleh bekerja tanpa izin sendiri. Kami urus sekali jalan untuk keluarga agar visanya sinkron dengan KITAS utama." },
    ],
    keywords: ["rptka", "kitas kerja", "notifikasi tka", "dpkk", "izin kerja orang asing"],
  },
  {
    id: "alkes",
    long: "Alat kesehatan & PKRT (Perlengkapan Kesehatan Rumah Tangga) wajib izin edar Kemenkes sebelum dipasarkan: AKD (Alat Kesehatan Dalam negeri) untuk produk lokal, AKL (Alat Kesehatan Luar negeri) untuk impor, dan IPAK untuk izin peredaran distributor. Kelas risiko A (rendah) sampai D (tinggi) menentukan proses & durasi evaluasi. Untuk supplement kosmetik ada jalur BPOM terpisah. Kami pandu seluruh alur: klasifikasi, dokumen teknis, uji lab, sampai label Kemenkes yang benar.",
    audience: ["Produsen", "Distributor", "Perusahaan"],
    legalBasis: "UU 17/2023 (Kesehatan), PP 28/2024, Permenkes alkes & PKRT",
    authority: "Kemenkes (Ditjen P2P & Farmasi/Alkes) via Kpom",
    requirements: [
      "NIB & badan usaha dengan KBLI alkes/PKRT",
      "Sertifikat CPOTB/CPOKB (pabrik) atau IPAK (distributor)",
      "Dokumen teknis produk: spesifikasi, komposisi, manual",
      "Sertifikat mutu (ISO 13485 untuk produsen tertentu)",
      "Sampel & label draft sesuai regulasi",
    ],
    steps: [
      "Klasifikasi produk & kelas risiko (A/B/C/D) via Kpom",
      "Persiapan dokumen teknis & quality management",
      "Pengajuan AKD/AKL/IPAK online + evaluasi Kemenkes",
      "Jawaban tanggap uji (bila ada) & revisi dokumen",
      "Terbit izin edar + panduan label & laporan pasca-pasar",
    ],
    faq: [
      { q: "Apa beda AKD, AKL, dan IPAK?", a: "AKD untuk alkes produksi dalam negeri, AKL untuk produk impor, IPAK untuk izin edaran distributor (tidak memproduksi). Semua diterbitkan Kemenkes dengan syarat & evaluasi berbeda. Kami bantu pilih jalur yang benar sesuai posisi Anda di rantai pasok." },
      { q: "Berapa lama izin edar alkes terbit?", a: "Kelas A/B: 30-60 hari. Kelas C/D: 60-120 hari (evaluasi lebih dalam, kadang butuh uji klinis). Tercepat bila dokumen teknis lengkap & jelas sejak pengajuan. Kami audit dokumen Anda terlebih dahulu supaya tidak bolak-balik revisi." },
      { q: "Thermometer, masker, kursi roda — semuanya perlu izin edar?", a: "Ya, semua alkes & PKRT yang dipasarkan (termasuk yang tampak sederhana) wajib izin edar Kemenkes. Pelaku yang sudah berjualan tanpa izin bisa kena pencabutan & sanksi peredaran. Kami bantu legalisasi batch yang sudah ada juga." },
    ],
    keywords: ["izin alkes", "akl kemenkes", "akd", "ipak", "izin edar alat kesehatan"],
  },
  {
    id: "pendidikan",
    long: "Lembaga pendidikan & pelatihan (LKP, bimbel, kursus, SD-SMA swasta, hingga training center) perlu legalitas berlapis: NIB + izin operasional Dinas Pendidikan/Disnaker, NPSN, sampai akreditasi BAN-PNF/LALPK untuk kredibilitas & akses program pemerintah. Jenis lembaga menentukan jalur: kursus umum (LKP), pelatihan kerja (LPK berizin), atau sekolah formal. Kami bantu dari struktur kurikulum, standar sarana, hingga SK operasional terbit.",
    audience: ["Individu", "UMKM", "Perusahaan"],
    legalBasis: "UU 20/2003 (Sisdiknas), PP 57/2021 (Pendidikan & Kebudayaan)",
    authority: "Dinas Pendidikan / Disnaker + Kemendikbudristek (NPSN, akreditasi)",
    requirements: [
      "NIB + badan usaha (atau yayasan untuk sekolah formal)",
      "Kurikulum & rencana pembelajaran yang jelas",
      "Sarana & prasarana sesuai standar (ruang kelas, alat)",
      "Tenaga pendidik dengan kualifikasi yang relevan",
      "Dokumen lokasi: PBG, bukti sewa/milik gedung",
    ],
    steps: [
      "Konsultasi jenis lembaga & program yang ditawarkan",
      "Penyusunan kurikulum, struktur organisasi & SOP",
      "Penerbitan NIB + izin operasional dinas terkait",
      "Pengajuan NPSN & verifikasi sarana (bila formal/LKP)",
      "Akreditasi BAN-PNF/LALPK & panduan laporan berkala",
    ],
    faq: [
      { q: "Bimbel/kursus online perlu izin?", a: "Ya — LKP online juga butuh izin operasional (bisa proses lebih ringan bila tanpa lokasi fisik permanen). Banyak pelaku online teaching mengabaikan ini, lalu kena pemblokiran saat ada laporan. Kami bantu legalisasi sejak awal agar aman bertumbuh." },
      { q: "Apa beda LPK dan LKP?", a: "LPK (Lembaga Pelatihan Kerja) fokus keterampilan kerja, berizin Disnaker, dapat mengintegrasikan penempatan PMI & program pemerintah. LKP (Lembaga Kursus & Pelatihan) lebih umum, izinnya Dinas Pendidikan. Kami pilihkan yang sesuai program Anda — atau keduanya bila program Anda menyentuh dua-duanya." },
      { q: "Akreditasi penting untuk kursus kecil?", a: "Untuk menampung siswa dana BOS/program pemerintah atau bekerja sama korporat — ya, akreditasi penting. Untuk kursus privat mandiri, izin operasional sudah cukup legal. Kami bantu strategi bertahap: izin dulu, akreditasi saat siap." },
    ],
    keywords: ["izin lembaga kursus", "izin lpk", "npsn", "akreditasi ban-pnf", "izin bimbel"],
  },
  {
    id: "pse-komdigi",
    long: "Setiap penyelenggara sistem elektronik (website, aplikasi, marketplace, fintech, OCR, hingga SaaS) wajib terdaftar PSE di Komdigi sesuai UU ITE & PP 71/2019 — dengan sanksi pemblokiran untuk yang lalai. Ada dua jenis: PSE Lingkup Publik (pemerintah) dan PSE Lingkup Privat (bisnis umum), dengan registrasi ringan untuk yang kecil dan registrasi berat untuk yang sistemnya besar. Tambah UU PDP (Perlindungan Data Pribadi) 2022, kepatuhan data pun jadi wajib. Kami urus registrasi penuh + checklist PDP agar platform Anda aman.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "UU ITE, PP 71/2019, UU 27/2022 (PDP), Permen Kominfo terkait PSE",
    authority: "Komdigi (Kementerian Komunikasi & Digital)",
    requirements: [
      "NIB & badan usaha (atau perseorangan untuk PSE kecil)",
      "Deskripsi sistem elektronik: fungsi, data yang diolah, dsb",
      "URL/aplikasi aktif (bisa staging untuk review)",
      "Kebijakan privasi & syarat layanan (kami bantu draft)",
      "Dokumen pengendali data (untuk kepatuhan PDP)",
    ],
    steps: [
      "Konsultasi jenis PSE & klasifikasi risiko sistem Anda",
      "Penyusunan dokumen deskripsi sistem & kebijakan privasi",
      "Pendaftaran online di portal PSE Komdigi",
      "Terbit Tanda Daftar PSE (dapat diverifikasi publik)",
      "Checklist kepatuhan PDP & panduan laporan insiden",
    ],
    faq: [
      { q: "Website company profile biasa juga wajib PSE?", a: "Umumnya ya, karena setiap sistem elektronik yang berinteraksi dengan pengguna (form, newsletter, login) masuk definisi PSE Privat. Untuk brochure tanpa interaksi, statusnya abu-abu — lebih aman terdaftar karena gratis & cepat. Kami bantu evaluasi gratis." },
      { q: "Apa risiko tidak terdaftar PSE?", a: "Pemblokiran akses dari Indonesia (seperti beberapa platform besar yang kena blok 2022), sanksi administratif, dan posisi hukum lemah saat sengketa data. Untuk startup yang akan fundraising, due diligence investor hampir selalu cek status PSE." },
      { q: "UU PDP mempengaruhi bisnis saya bagaimana?", a: "UU 27/2022 mengatur pengumpulan, penyimpanan, & penggunaan data pribadi — wajib consent, hak subjek data, laporan insiden 3x24 jam, dan dsb. Untuk aplikasi/marketplace yang pegang data pelanggan, kepatuhan ini wajib sejak masa transisi berlaku. Kami bantu gap analysis & perbaikan." },
    ],
    keywords: ["pse komdigi", "tanda daftar pse", "registrasi pse", "uu pdp", "izin aplikasi"],
  },
  {
    id: "lkpm",
    long: "LKPM (Laporan Kegiatan Penanaman Modal) adalah kewajiban berkala setiap pelaku usaha dengan NIB — triwulan (UMKM kecil), semester (menengah/besar), atau tahunan — lewat OSS. Banyak pelaku usaha tidak tahu kewajiban ini sampai NIB mereka masuk status 'non-aktif' atau terancam pencabutan saat butuh perpanjangan izin, RPTKA, atau tender. Kami buat sistem: kalendar kewajiban, penyusunan data, pengunggahan tepat waktu, dan penanganan sanksi bila sudah telanjur lalai.",
    audience: ["UMKM", "Perusahaan"],
    legalBasis: "PP 5/2021, Peraturan BKPM No. 5/2021 (LKPM)",
    authority: "OSS-RBA (Kementerian Investasi/BKPM)",
    requirements: [
      "NIB aktif & akses akun OSS",
      "Data aktivitas usaha: omzet, karyawan, investasi, ekspor (jika ada)",
      "Laporan keuangan internal sederhana (bisa dari pembukuan)",
      "Untuk telat: dokumen justifikasi keterlambatan",
    ],
    steps: [
      "Audit status LKPM Anda saat ini (telat berapa periode?)",
      "Penyusunan data & narasi laporan yang tepat",
      "Pengunggahan LKPM via OSS-RBA + konfirmasi status",
      "Setup kalendar kewajiban otomatis ke depan",
      "Penanganan sanksi/regularisasi bila ada status melanggar",
    ],
    faq: [
      { q: "Apa risiko kalau tidak lapor LKPM?", a: "NIB bisa dianggap tidak aktif, terancam pencabutan administratif, dan menjadi hambatan saat butuh: perpanjangan izin, RPTKA (tenaga asing), API, atau tender. Biaya regularisasi jauh lebih mahal daripada lapor tepat waktu — mulai rapikan sekarang." },
      { q: "LKPM itu isinya apa saja?", a: "Ringkasan aktivitas usaha: investasi yang direalisasi, omzet, jumlah pekerja, produksi/penjualan, ekspor (bila ada), dan kendala. Untuk UMKM kecil datanya cukup sederhana — bisa disusun dari pembukuan kas. Kami bantu template & susun data Anda." },
      { q: "Saya telat 2 tahun, masih bisa dibantu?", a: "Bisa. Kami tangani regularisasi: susun semua laporan tertunda, ajukan dengan justifikasi yang tepat, dan negotiasi sanksi bila ada. Biasanya prosesnya 2-4 minggu tergantung jumlah periode. Lebih baik rapikan sekarang sebelum butuh izin lain." },
    ],
    keywords: ["lkpm", "laporan lkpm", "kewajiban oss", "lkpm telat", "lkap oss"],
  },
  {
    id: "b3-proper",
    long: "Pengelolaan limbah B3 (Bahan Berbahaya & Beracun) diatur ketat: izin simpan, angkut, olah, dan buang semuanya berizin, dengan TPS LB3 (Tempat Penyimpanan Sementara) sebagai titik awal. Untuk perusahaan besar, ada PROPER (Program Penilaian Peringkat Kinerja) KLHK dengan peringkat biru-hijau-emas yang mempengaruhi reputasi & izin lanjutan. Kami bantu dari izin TPS LB3, kontrak pihak ketiga pengolah B3, laporan ritreg, hingga peningkatan peringkat PROPER.",
    audience: ["Perusahaan"],
    legalBasis: "PP 22/2021, PP 74/2001 (B3), Permen LHK PROPER",
    authority: "KLHK / DLH (Dinas Lingkungan Hidup)",
    requirements: [
      "NIB & izin lingkungan (SPPL/UKL-UPL/AMDAL) aktif",
      "Identifikasi jenis & volume limbah B3 yang dihasilkan",
      "Desain TPS LB3 sesuai standar (ventilasi, tanggul, tanda)",
      "Kontrak dengan pihak ketiga pengangkut/pengolah B3 berizin",
      "Dokumen ritreg (riwayat penyimpanan B3) rutin",
    ],
    steps: [
      "Audit jenis limbah & status kepatuhan B3 saat ini",
      "Penyusunan desain TPS LB3 + dokumen izin",
      "Pengajuan izin TPS LB3 ke DLH/KLHK",
      "Setup kontrak pengolahan & sistem ritreg",
      "Persiapan PROPER (bila relevan) & laporan berkala",
    ],
    faq: [
      { q: "Bengkel kecil/katering punya limbah B3 juga?", a: "Bila menghasilkan B3 (oli bekas, baterai, bahan kimia) — ya, ada kewajiban pengelolaan meski skala kecil. Pihak yang disebut 'penghasil B3 non-spesifik' tetap wajib ikut aturan. Kami bantu skema ringan yang sesuai skala usaha kecil." },
      { q: "Apa manfaat PROPER biru/hijau?", a: "PROPER hijau/emas membuka akses: tender pemerintah, kredit bank hijau, investor ESG, dan reputasi publik. Biru adalah baseline patuh. Perusahaan yang proaktif lingkungan biasanya dapat harga premium & relasi lebih baik — kami bantu jalur peningkatan peringkat." },
      { q: "Berapa biaya izin TPS LB3?", a: "Mulai Rp10 juta untuk izin & dokumen (tergantung jenis limbah & skala). Ditambah biaya kontrak pengolah pihak ketiga yang bervariasi per jenis. Kami beri estimasi detail setelah audit limbah Anda." },
    ],
    keywords: ["izin b3", "tps lb3", "proper", "izin limbah", "ritreg b3"],
  },
  {
    id: "ekspansi-asing",
    long: "Membawa bisnis Indonesia ke luar negeri kini lebih mudah: Singapura (Pte Ltd — 1 hari, 100% milik asing, pajak 17%), Malaysia (Sdn Bhd), Dubai/UEA (Free Zone — 100% kepemilikan, tanpa pajak pribadi), AS (LLC/L-Corp untuk akses pasar besar), Hong Kong, sampai Arab Saudi (MISA era Vision 2030). Setiap yurisdiksi punya karakter: tax haven, akses pasar, regulasi perbankan. Kami bandingkan opsi berdasar tujuan bisnis Anda, lalu urus pendirian, registered address, bank account, dan kepatuhan tahunan penuh.",
    audience: ["Perusahaan", "Investor"],
    legalBasis: "Regulasi yurisdiksi tujuan (ACRA Singapore, MISA Saudi, DED Dubai, dsb)",
    authority: "Lembaga registrasi negara tujuan + partner lokal kami",
    requirements: [
      "Legalitas badan usaha Indonesia (akta, NIB, laporan keuangan)",
      "Paspor direksi/pemegang saham",
      "Struktur kepemilikan yang diinginkan (holding/subsidiary)",
      "Rencana bisnis singkat & tujuan pendirian",
      "Dana setoran modal awal (bervariasi per negara)",
    ],
    steps: [
      "Konsultasi tujuan ekspansi → rekomendasi yurisdiksi optimal",
      "Penyusunan dokumen & verifikasi KYC semua pemegang saham",
      "Pengajuan pendirian di yurisdiksi terpilih",
      "Pembukaan bank account (kami pandu persyaratan bank lokal)",
      "Setup kepatuhan tahunan: pajak, audit, laporan lokal",
    ],
    faq: [
      { q: "Singapura vs Dubai, mana lebih baik?", a: "Tergantung tujuan: Singapura kuat untuk holding & akses ASEAN dengan reputasi perbankan tinggi; Dubai kuat untuk tax optimization & akses Timur Tengah. AS LLC bagus untuk bisnis digital global. Kami bedah kebutuhan Anda lalu rekomendasi yang paling efisien." },
      { q: "Apakah harus punya kantor fisik di sana?", a: "Tidak selalu. Singapura & Dubai memungkinkan registered address virtual (layanan resmi). Beberapa yurisdiksi (Arab Saudi, Jerman) butuh kantor nyata untuk lisensi tertentu. Kami sediakan opsi address + mailbox sesuai kebutuhan." },
      { q: "Setelah pendirian, pajaknya bagaimana?", a: "Tergantung yurisdiksi & reziden tax: Singapura 17% (dengan banyak insentif), Dubai 0% (Free Zone, dengan syarat), AS tergantung state. Penting: penduduk Indonesia tetap wajib lapor pajak global sesuai aturan Indonesia (dengan tax credit). Kami koordinasi dengan tax advisor agar struktur Anda patuh dua-duanya." },
    ],
    keywords: ["pendirian pt singapura", "pt dubai", "misa saudi", "llc amerika", "ekspansi luar negeri"],
  },
];

/** Mapping id SERVICES → id PERMIT_GUIDES untuk reuse konten */
export const GUIDE_MAP: Record<string, string> = {
  nib: "nib",
  pt: "pt",
  cv: "cv",
  halal: "halal",
  bpom: "bpom",
  pbg: "pbg",
  lingkungan: "lingkungan",
  kesehatan: "klinik",
  "ppi-umroh": "ppi-umroh",
  "ppi-haji": "ppi-haji",
  iata: "iata",
  "saudi-arabia": "saudi-arabia",
  "rkab-tambang": "rkab-tambang",
};

/** Layanan yang ada di PERMIT_GUIDES (ambil requirements/steps/faq dari sana) */
export const GUIDE_BASED_IDS = new Set(Object.keys(GUIDE_MAP));

/** Layanan manual (LICENSE_DETAILS) untuk lookup cepat */
export const LICENSE_DETAIL_MAP = new Map(LICENSE_DETAILS.map((d) => [d.id, d]));
